-- Hand-authored (T002): no live Postgres/PostGIS instance is reachable in
-- this environment (`prisma migrate dev` fails with P1000 against the
-- placeholder DATABASE_URL, and the local Docker daemon is not running),
-- so this SQL was derived directly from the schema.prisma diff rather than
-- generated by `prisma migrate dev`. It follows the exact DDL conventions
-- of the three prior migrations in this project (column types, naming,
-- constraint/index naming). MUST be verified by running
-- `prisma migrate dev`/`prisma migrate deploy` against a real database
-- before this feature is considered done (see tasks.md T002's Verification
-- note and quickstart.md's Production Readiness Checklist).

-- CreateTable
CREATE TABLE "AnalysisRun" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "operationType" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "parameters" JSONB NOT NULL,
    "inputLayerIds" JSONB NOT NULL,
    "resultLayerId" TEXT,
    "resultData" JSONB,
    "errorMessage" TEXT,
    "batchId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AnalysisRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AnalysisRun_projectId_createdAt_idx" ON "AnalysisRun"("projectId", "createdAt");

-- CreateIndex
CREATE INDEX "AnalysisRun_batchId_idx" ON "AnalysisRun"("batchId");

-- AddForeignKey
ALTER TABLE "AnalysisRun" ADD CONSTRAINT "AnalysisRun_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AnalysisRun" ADD CONSTRAINT "AnalysisRun_resultLayerId_fkey" FOREIGN KEY ("resultLayerId") REFERENCES "Layer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
