import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"
import { listShapefilesInArchive, parseShapefile } from "../shapefileParser"

/**
 * Shapefile parser tests (specs/005-import-export, T142; FR-017–FR-021, FR-082,
 * FR-083).
 *
 * Every fixture is a real ZIP holding a real `.shp`/`.shx`/`.dbf`/`.prj` set,
 * generated by `@mapbox/shp-write` — not a hand-mocked archive. A shapefile
 * reader tested against fabricated bytes proves nothing about a shapefile.
 */

const FIXTURES = resolve(process.cwd(), "src/features/import-export/__tests__/fixtures")

function zipFile(name: string): File {
  return new File([readFileSync(resolve(FIXTURES, name))], name, { type: "application/zip" })
}

describe("parseShapefile — one file, no multi-select (FR-017)", () => {
  it("reads a whole ZIP and returns its features", async () => {
    const result = await parseShapefile(zipFile("parcels_osgb.zip"), {})

    // The user selects one file. The component set is resolved internally — the
    // workflow the old loose-file path existed to eliminate.
    expect(result.features).toHaveLength(5)
    expect(result.features[0].sourcePosition).toBe(0)
  })

  it("finds the component set inside a nested directory (FR-017 scenario 2)", async () => {
    const result = await parseShapefile(zipFile("parcels_nested.zip"), {})

    // `data/gis/parcels.*` — the base path simply carries its directory prefix.
    expect(result.features).toHaveLength(5)
  })
})

describe("parseShapefile — coordinates stay in the source CRS (research.md D4)", () => {
  it("returns untransformed eastings and northings", async () => {
    const result = await parseShapefile(zipFile("parcels_osgb.zip"), {})
    const [x, y] = result.features[0].geometry.coordinates as [number, number]

    // 530034 E / 180381 N, not -0.1276 / 51.5072. `shpjs`'s convenience entry
    // point would have reprojected these with proj4 before returning; the
    // low-level API is used precisely so it does not, leaving the persisted
    // transform to PostGIS `ST_Transform`.
    expect(x).toBeCloseTo(530034, 0)
    expect(y).toBeCloseTo(180381, 0)
  })
})

describe("parseShapefile — CRS detection from .prj (FR-019, FR-062, FR-063)", () => {
  it("extracts the EPSG authority code from the .prj's WKT", async () => {
    const result = await parseShapefile(zipFile("parcels_osgb.zip"), {})

    expect(result.detectedCrs).toBe("EPSG:27700")
    // No manual selection is required when the archive declares its system.
    expect(result.detectedCrsDefinition).toBeUndefined()
  })

  it("falls back to a custom definition when the WKT carries no authority (FR-063)", async () => {
    const result = await parseShapefile(zipFile("parcels_custom_prj.zip"), {})

    expect(result.detectedCrs).toBe("CUSTOM")
    // PostGIS accepts proj4/WKT text directly, so no spatial_ref_sys row is needed.
    expect(result.detectedCrsDefinition).toMatch(/PROJCS\["Local Grid"/)
  })

  it("reports no CRS at all when there is no .prj, so the user must choose (FR-062)", async () => {
    const result = await parseShapefile(zipFile("parcels_no_prj.zip"), {})

    expect(result.detectedCrs).toBeNull()
    expect(
      result.warnings.some((warning) => /no \.prj file/i.test(warning.message)),
    ).toBe(true)
  })
})

describe("parseShapefile — DBF attributes (FR-008, FR-020)", () => {
  it("routes DBF records through the shared attribute path", async () => {
    const result = await parseShapefile(zipFile("parcels_osgb.zip"), {})
    const first = result.features[0].properties

    expect(first.WARD).toBe("Holborn")
    // Numeric DBF fields arrive as text, like every other format's numbers.
    expect(first.POP).toMatch(/^\d+/)
    expect(first.UPRN).toBe("100023336950")
  })

  it("preserves accented values rather than producing mojibake (FR-020)", async () => {
    const result = await parseShapefile(zipFile("parcels_latin1.zip"), {})
    const values = result.features.map((feature) => feature.properties.QUARTIER)

    expect(values).toContain("Île de Nantes")
    expect(values).toContain("Croix-Rousse")
    // The classic symptom of a mis-read code page.
    expect(values.some((value) => value.includes("Ã"))).toBe(false)
  })

  it("honours an explicit encoding override", async () => {
    const result = await parseShapefile(zipFile("parcels_latin1.zip"), { encoding: "UTF-8" })
    expect(result.features).toHaveLength(3)
  })

  it("reports missing attributes rather than failing when there is no .dbf (FR-018)", async () => {
    const result = await parseShapefile(zipFile("parcels_no_dbf.zip"), {})

    // Geometry is still readable, so the import is offered with a warning rather
    // than refused outright.
    expect(result.features).toHaveLength(5)
    expect(result.warnings.some((warning) => /\.dbf/i.test(warning.message))).toBe(true)
    expect(result.features[0].properties).toEqual({})
  })
})

describe("parseShapefile — multiple shapefiles in one archive (FR-021)", () => {
  it("lists every shapefile without parsing any of them", async () => {
    const names = await listShapefilesInArchive(zipFile("parcels_multi.zip"))
    expect(names).toEqual(["parcels", "roads"])
  })

  it("reports the choice on the result so the dialog can offer it", async () => {
    const result = await parseShapefile(zipFile("parcels_multi.zip"), {})
    expect(result.availableLayers).toEqual(["parcels", "roads"])
  })

  it("defaults to the first shapefile alphabetically", async () => {
    const result = await parseShapefile(zipFile("parcels_multi.zip"), {})
    expect(result.features).toHaveLength(5)
    expect(result.features[0].properties.WARD).toBe("Holborn")
  })

  it("reads the named shapefile when one is chosen", async () => {
    const result = await parseShapefile(zipFile("parcels_multi.zip"), { shapefileName: "roads" })

    expect(result.features).toHaveLength(2)
    expect(result.features[0].properties.ROAD).toBe("Route 0")
  })

  it("rejects a name that is not in the archive, listing what is", async () => {
    await expect(
      parseShapefile(zipFile("parcels_multi.zip"), { shapefileName: "rivers" }),
    ).rejects.toThrow(/no shapefile named "rivers"[\s\S]*parcels, roads/)
  })

  it("omits availableLayers when the archive holds only one shapefile", async () => {
    const result = await parseShapefile(zipFile("parcels_osgb.zip"), {})
    expect(result.availableLayers).toBeUndefined()
  })
})

describe("parseShapefile — archive safety (FR-082, FR-083)", () => {
  /**
   * FR-082's guard is `assertArchiveEntryPath`, and it is applied to every entry
   * name during enumeration, before any entry is decompressed. Its own behaviour
   * is covered directly in `fileGuards.test.ts`, because a fixture cannot reach
   * it: **JSZip normalizes `..` segments away when the archive is loaded**, so
   * `../../evil.shp` arrives as `evil.shp` and the guard never sees a traversal.
   *
   * That normalization is JSZip's, not this codebase's, which is exactly why the
   * guard stays: it is defence in depth against a future change in how archives
   * are read, and it costs one comparison per entry.
   */
  it("handles a zip-slip archive safely — the escaping entry is contained, not honoured", async () => {
    // `../../evil.shp` is flattened to `evil.shp` by JSZip, so the archive reads
    // as an ordinary one holding a shapefile called `evil` with no `.dbf`.
    // Nothing is written outside the archive's own contents — and nothing could
    // be, because this parser never writes to a filesystem at all: it reads
    // entries into memory and posts normalized features back.
    const result = await parseShapefile(zipFile("evil_zipslip.zip"), {})

    expect(result.features.length).toBeGreaterThan(0)
    expect(result.warnings.some((warning) => /\.dbf/i.test(warning.message))).toBe(true)
  })

  it("lists no shapefile for a zip-slip archive rather than resolving the escaped path", async () => {
    const names = await listShapefilesInArchive(zipFile("evil_zipslip.zip"))
    // `evil` — inside the root, not two directories above it.
    expect(names.every((name) => !name.includes(".."))).toBe(true)
  })

  it("rejects an archive with no .shp at all", async () => {
    const { default: JSZip } = await import("jszip")
    const zip = new JSZip()
    zip.file("notes.txt", "nothing here")
    const buffer = await zip.generateAsync({ type: "arraybuffer" })

    await expect(
      parseShapefile(new File([buffer], "empty.zip", { type: "application/zip" }), {}),
    ).rejects.toThrow(/contains no \.shp file/i)
  })
})

describe("parseShapefile — cancellation", () => {
  it("honours an already-aborted signal", async () => {
    const controller = new AbortController()
    controller.abort()

    await expect(
      parseShapefile(zipFile("parcels_osgb.zip"), { signal: controller.signal }),
    ).rejects.toThrow()
  })
})
